trigger:
- feature/YSP-800-devbranchUpdate
 
pool:
  vmImage: 'ubuntu-latest'
 
steps:
- checkout: self
 
- script: |
    git checkout feature/YSP-800-devbranchUpdate
    git checkout b2bSellingPathDev
    git pull
    git checkout feature/YSP-800-devbranchUpdate
    git merge b2bSellingPathDev
    git push
  displayName: 'Merge and Push Branches'
